name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag ytdownloader:$(date +%s)

      - name: Log in to Azure Container Registry
        run: |
          echo "${{ secrets.PASSWORD }}" | docker login brightstraining24fall.azurecr.io --username ${{ secrets.USERNAME }} --password-stdin

      - name: Tag Docker image
        run: |
          docker tag ytdownloader:latest brightstraining24fall.azurecr.io/fredrik/ytdownloader

      - name: Push Docker image
        run: |
          docker push brightstraining24fall.azurecr.io/fredrik/ytdownloader:$(date +%s)
